# Model arguments
model_name_or_path: codellama/CodeLlama-7b-Instruct-hf
torch_dtype: bfloat16

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ message['content'] + ' [/INST]' }}\n{% elif message['role'] == 'system' %}\n{{ '[INST] ' + message['content'] }}{% elif message['role'] == 'assistant' %}{{ message['content'] }}\n{% endif %}\n{% endfor %}"
dataset_dir: ./datasets/dataset_binarized
preprocessing_num_workers: 12

# DPO trainer config
bf16: true
optim: adamw_8bit
beta: 0.1
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-5
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 5
output_dir: ./runs/codellama-7b-instruct-dpo-qlora
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
save_strategy: "epoch"
save_total_limit: 5
seed: 42
warmup_ratio: 0.1