# Model arguments
model_name_or_path: coseal/CodeLlama-7B-Instruct-sft-dpo-qlora
model_name: codellama-7b-instruct-sft-dpo-qlora

# Data arguments
dataset_name_or_path: coseal/codal-bench
dataset_split: test
output_dir: runs/eval_results/
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"

# Generation config
max_new_tokens: 1024
greedy: True