# Model arguments
model_name_or_path: TheBloke/Mistral-7B-Instruct-v0.2-GPTQ
revision: gptq-4bit-32g-actorder_True
model_name: mistral-7b-instruct

# Data arguments
dataset_name_or_path: datasets/dataset_splits
dataset_split: test
output_dir: runs/eval_results/
chat_template: "{% for message in messages %}{% if message['role'] == 'user' %}{{ bos_token + '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% endif %}{% endfor %}"

# Generation config
max_new_tokens: 1024
greedy: True